In [31]:
## Neural Network Examples 

import numpy as np 

## Logical AND 

"""
One Input Layer, One Output, No Hidder Layers
"""

# X is a 2 x 1 np array ( matrix) 
x0 = 1
x1 = 0
x2 = 1

X = np.array( [
    [x0],
    [x1],
    [x2],
])

# I've made my Theta a list of arrays 
theta = []

#Initialize theta0 to pretrained values
theta0 = np.array([
    [-30],
    [20],
    [20],
])

#Append Theta0
theta.append( theta0 )


"""  IGNORE
# This is a Helper Function for the next function
# # Round up or down depending on value given
# def logistic_round(value):
#     if value >= 0.5:
#         return 1
#     else:
#         return 0
"""

#Sigmoid is our activation function
def sigmoid(X):
    return 1 / (1 + np.exp(-X) )

    
# theta' * X
z1 = theta[0].T.dot( X )

print(X.shape)

# # a1 is our output
a1 = sigmoid(z1)

# Our Hypothesis for this single example
print ( round(a1[0][0]) ) 

(3, 1)


0.0

In [54]:
# Batching Examples

import pprint as pp

#Let X be a matrix where each column is a case
X = np.empty([3,4])

#Create a function to generate all four logic AND cases
for i in range(2):
    for j in range(2):
#         print("i: {}".format(i), "j: {}".format(j))
        np.append(
            X, 
            np.array([
                [1],
                [i],
                [j],
            ]),
        )

print("This is what the cases look like:\n", X, sep="\n")


#Theta is already defined, so let's perform a batch computation on the four cases
z = theta[0].T.dot( X )
a = sigmoid(z)

print ("\nHere is the output.", "Each column is a different case:", a, sep="\n" )

i: 0 j: 0
i: 0 j: 1
i: 1 j: 0
i: 1 j: 1
This is what the cases look like:

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Here is the output.
Each column is a different case:
[[0.5 0.5 0.5 0.5]]


In [ ]:
"""
Not sure why X isn't being built properly 
I'll deal with that next time around, maybe.  
"""